"""Initial migration

Revision ID: 58f7e2d6b31f
Revises: ead416863cac
Create Date: 2026-02-15 18:00:16.102792+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '58f7e2d6b31f'
down_revision = 'ead416863cac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
